name: blip-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pillow
  - pip:
      - transformers==4.41.0
      - accelerate
      - safetensors
